import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type LanguageCode = 'en' | 'hi' | 'or' | 'bn' | 'te' | 'ta' | 'mr';

export interface LanguageOption {
  code: LanguageCode;
  label: string;
  nativeLabel: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', label: 'English', nativeLabel: 'English' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिंदी' },
  { code: 'or', label: 'Odia', nativeLabel: 'ଓଡ଼ିଆ' },
  { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা' },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்' },
  { code: 'mr', label: 'Marathi', nativeLabel: 'मराठी' },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Brand & Header
    'brand.name': 'S.I.R.I.S',
    'brand.tagline': 'Odisha Police Intelligence',
    'header.station': 'STATION',
    'header.stateCommand': 'ODISHA POLICE · STATE COMMAND',
    'header.engineRunning': 'Intelligence Engine Running...',
    'header.newIntel': 'NEW INTELLIGENCE DISCOVERED:',
    'header.viewDetails': 'VIEW DETAILS',
    'header.language': 'Language',

    // Sidebar Section Headers
    'nav.section.myDesk': 'MY DESK',
    'nav.section.investigate': 'INVESTIGATE',
    'nav.section.intelligence': 'INTELLIGENCE',
    'nav.section.assistance': 'ASSISTANCE',
    'nav.section.reports': 'REPORTS',
    'nav.section.stateCommand': 'STATE COMMAND',
    'nav.section.policeAdmin': 'POLICE ADMINISTRATION',
    'nav.section.caseIntel': 'CASE INTELLIGENCE',
    'nav.section.networkIntel': 'NETWORK INTELLIGENCE',
    'nav.section.operations': 'OPERATIONS',
    'nav.section.system': 'SYSTEM',

    // Nav Items
    'nav.dashboard': 'Dashboard',
    'nav.commandCenter': 'Command Center',
    'nav.myInvestigations': 'My Investigations',
    'nav.accessRequests': 'Access Requests',
    'nav.registerFir': 'Register FIR',
    'nav.evidenceVault': 'Evidence Vault',
    'nav.caseSearch': 'Case Search',
    'nav.allCases': 'All Cases',
    'nav.networkExplorer': 'Network Explorer',
    'nav.crimeIntelligence': 'Crime Intelligence',
    'nav.legalIntelligence': 'Legal Intelligence',
    'nav.aiAssistant': 'AI Assistant',
    'nav.caseReports': 'Case Reports',
    'nav.policeStations': 'Police Stations',
    'nav.officers': 'Officers',
    'nav.monthlyReports': 'Monthly Crime Reports',
    'nav.notifications': 'Notifications',
    'nav.profile': 'Profile',

    // Dashboard UI
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Real-time overview of investigations and intelligence insights',
    'dashboard.filters': 'Filters',
    'dashboard.resetFilters': 'Reset Filters',
    'dashboard.district': 'District',
    'dashboard.category': 'Crime Category',
    'dashboard.priority': 'Priority',
    'dashboard.activeCases': 'ACTIVE CASES',
    'dashboard.pendingCases': 'PENDING CASES',
    'dashboard.highPriority': 'HIGH PRIORITY',
    'dashboard.intelAlerts': 'INTEL ALERTS',
    'dashboard.totalFirs': 'Total FIRs',
    'dashboard.casesClosed': 'Cases Closed',
    'dashboard.overdueWork': 'Overdue Work',
    'dashboard.activeOfficers': 'Active Officers',
    'dashboard.firTrend': 'FIR Registration Trend',
    'dashboard.casesByCrime': 'Cases by Crime Category',
    'dashboard.crimeHotspots': 'Crime Hotspots (This Month)',
    'dashboard.crossStation': 'Cross-Station Links',
    'dashboard.activeInvestigations': 'Active Investigations',
    'dashboard.intelligenceAlerts': 'Intelligence Alerts',
    'dashboard.resolved': 'RESOLVED',
    'dashboard.pending': 'PENDING',
    'dashboard.closureRate': 'CLOSURE RATE',
    'dashboard.viewAll': 'View All',
    'dashboard.openCase': 'Open Case Workspace',
    'dashboard.caseId': 'Case ID',
    'dashboard.caseTitle': 'Case Title',
    'dashboard.officer': 'Investigating Officer',
    'dashboard.risk': 'Risk',
    'dashboard.daysActive': 'Days Active',
    'dashboard.progress': 'Progress',
    'dashboard.highStrength': 'High Strength',
    'dashboard.mediumStrength': 'Medium',
    'dashboard.lowStrength': 'Low',
    'dashboard.days': 'days',
    'dashboard.thisMonth': 'This Month',
    'dashboard.last30Days': 'Last 30 Days',
    'dashboard.thisQuarter': 'This Quarter',

    // Categories
    'cat.cyber': 'Cyber Crime',
    'cat.financial': 'Financial Fraud',
    'cat.theft': 'Theft',
    'cat.extortion': 'Extortion',
    'cat.assault': 'Assault',
    'cat.other': 'Other Crimes',

    // Common Buttons
    'btn.runAiAnalysis': 'Run AI Analysis',
    'btn.confirmCreateCase': 'Confirm & Create Case Workspace',
    'btn.processEvidence': 'Process Evidence',
    'btn.requestAccess': 'Request Access',
    'btn.search': 'Search',
    'btn.reset': 'Reset',
    'btn.downloadPdf': 'Download PDF',
    'btn.cancel': 'Cancel',
    'btn.close': 'Close',

    // AIRA & Voice Intelligence
    'aira.greeting': 'Good day, Inspector. I am AIRA, your voice intelligence assistant.',
    'aira.listening': 'LISTENING ACTIVE',
    'aira.analyzing': 'AIRA ANALYZING',
    'aira.tapToSpeak': 'Tap to Speak Command',
    'aira.audioPlaying': 'Speaking Response...',
    'aira.playAudio': 'Play Voice',
    'aira.replayAudio': 'Replay Voice',
    'aira.pauseAudio': 'Pause Voice',
    'aira.stopAudio': 'Stop Voice',

    // Legal Intelligence
    'legal.title': 'Legal Intelligence',
    'legal.applicableProvisions': 'Applicable Provisions',
    'legal.bnsLibrary': 'BNS Provisions Library',
    'legal.disclaimerTitle': 'AI-Assisted Legal Intelligence',
    'legal.disclaimerText': 'Requires authorized officer review. Does not constitute final legal determination.',
    'legal.clickToView': 'Click to view full provision',
    'legal.relevance': 'Relevance',
    'legal.keyElements': 'Key Elements',
  },
  hi: {
    // Brand & Header
    'brand.name': 'S.I.R.I.S',
    'brand.tagline': 'ओडिशा पुलिस इंटेलिजेंस',
    'header.station': 'थाना',
    'header.stateCommand': 'ओडिशा पुलिस · राज्य कमान',
    'header.engineRunning': 'इंटेलिजेंस इंजन सक्रिय...',
    'header.newIntel': 'नई खुफिया जानकारी खोजी गई:',
    'header.viewDetails': 'विवरण देखें',
    'header.language': 'भाषा',

    // Sidebar
    'nav.section.myDesk': 'मेरा डेस्क',
    'nav.section.investigate': 'जांच',
    'nav.section.intelligence': 'इंटेलिजेंस',
    'nav.section.assistance': 'सहायता',
    'nav.section.reports': 'रिपोर्ट',
    'nav.section.stateCommand': 'राज्य कमान',
    'nav.section.policeAdmin': 'पुलिस प्रशासन',
    'nav.section.caseIntel': 'केस इंटेलिजेंस',
    'nav.section.networkIntel': 'नेटवर्क इंटेलिजेंस',
    'nav.section.operations': 'संचालन',
    'nav.section.system': 'सिस्टम',

    'nav.dashboard': 'डैशबोर्ड',
    'nav.commandCenter': 'कमांड सेंटर',
    'nav.myInvestigations': 'मेरी जांचें',
    'nav.accessRequests': 'एक्सेस अनुरोध',
    'nav.registerFir': 'एफआईआर दर्ज करें',
    'nav.evidenceVault': 'साक्ष्य वॉल्ट',
    'nav.caseSearch': 'केस खोज',
    'nav.allCases': 'सभी मामले',
    'nav.networkExplorer': 'नेटवर्क एक्सप्लोरर',
    'nav.crimeIntelligence': 'अपराध इंटेलिजेंस',
    'nav.legalIntelligence': 'कानूनी इंटेलिजेंस',
    'nav.aiAssistant': 'एआई सहायक',
    'nav.caseReports': 'केस रिपोर्ट',
    'nav.policeStations': 'पुलिस स्टेशन',
    'nav.officers': 'अधिकारी',
    'nav.monthlyReports': 'मासिक अपराध रिपोर्ट',
    'nav.notifications': 'सूचनाएं',
    'nav.profile': 'प्रोफ़ाइल',

    // Dashboard UI
    'dashboard.title': 'डैशबोर्ड',
    'dashboard.subtitle': 'जांच और खुफिया जानकारी का रीयल-टाइम अवलोकन',
    'dashboard.filters': 'फ़िल्टर',
    'dashboard.resetFilters': 'फ़िल्टर रीसेट करें',
    'dashboard.district': 'ज़िला',
    'dashboard.category': 'अपराध श्रेणी',
    'dashboard.priority': 'प्राथमिकता',
    'dashboard.activeCases': 'सक्रिय मामले',
    'dashboard.pendingCases': 'लंबित मामले',
    'dashboard.highPriority': 'उच्च प्राथमिकता',
    'dashboard.intelAlerts': 'खुफिया अलर्ट',
    'dashboard.totalFirs': 'कुल एफआईआर',
    'dashboard.casesClosed': 'निपटाए गए मामले',
    'dashboard.overdueWork': 'विलंबित कार्य',
    'dashboard.activeOfficers': 'सक्रिय अधिकारी',
    'dashboard.firTrend': 'एफआईआर पंजीकरण रुझान',
    'dashboard.casesByCrime': 'अपराध श्रेणी अनुसार मामले',
    'dashboard.crimeHotspots': 'अपराध हॉटस्पॉट (इस माह)',
    'dashboard.crossStation': 'क्रॉस-स्टेशन संबंध',
    'dashboard.activeInvestigations': 'सक्रिय जांच',
    'dashboard.intelligenceAlerts': 'खुफिया अलर्ट',
    'dashboard.resolved': 'सुलझाए गए',
    'dashboard.pending': 'लंबित',
    'dashboard.closureRate': 'समाधान दर',
    'dashboard.viewAll': 'सभी देखें',
    'dashboard.openCase': 'केस वर्कस्पेस खोलें',
    'dashboard.caseId': 'केस आईडी',
    'dashboard.caseTitle': 'केस शीर्षक',
    'dashboard.officer': 'जांच अधिकारी',
    'dashboard.risk': 'जोखिम',
    'dashboard.daysActive': 'सक्रिय दिन',
    'dashboard.progress': 'प्रगति',
    'dashboard.highStrength': 'उच्च शक्ति',
    'dashboard.mediumStrength': 'मध्यम',
    'dashboard.lowStrength': 'निम्न',
    'dashboard.days': 'दिन',
    'dashboard.thisMonth': 'इस माह',
    'dashboard.last30Days': 'पिछले 30 दिन',
    'dashboard.thisQuarter': 'इस तिमाही',

    // Categories
    'cat.cyber': 'साइबर अपराध',
    'cat.financial': 'वित्तीय धोखाधड़ी',
    'cat.theft': 'चोरी',
    'cat.extortion': 'जबरन वसूली',
    'cat.assault': 'हमला',
    'cat.other': 'अन्य अपराध',

    'btn.runAiAnalysis': 'एआई विश्लेषण चलाएं',
    'btn.confirmCreateCase': 'पुष्टि करें और केस बनाएं',
    'btn.processEvidence': 'साक्ष्य संसाधित करें',
    'btn.requestAccess': 'एक्सेस का अनुरोध करें',
    'btn.search': 'खोजें',
    'btn.reset': 'रीसेट',
    'btn.downloadPdf': 'पीडीएफ डाउनलोड करें',
    'btn.cancel': 'रद्द करें',
    'btn.close': 'बंद करें',

    // AIRA & Voice Intelligence
    'aira.greeting': 'नमस्ते इंस्पेक्टर। मैं आयरा (AIRA) हूँ, आपकी वॉयस इंटेलिजेंस साथी।',
    'aira.listening': 'सुनना सक्रिय है',
    'aira.analyzing': 'आयरा विश्लेषण कर रही है',
    'aira.tapToSpeak': 'बोलने के लिए टैप करें',
    'aira.audioPlaying': 'प्रतिक्रिया बोल रही है...',
    'aira.playAudio': 'आवाज चलाएं',
    'aira.replayAudio': 'पुनः सुनें',
    'aira.pauseAudio': 'रोकें',
    'aira.stopAudio': 'बंद करें',

    // Legal Intelligence
    'legal.title': 'कानूनी इंटेलिजेंस (BNS)',
    'legal.applicableProvisions': 'लागू प्रावधान',
    'legal.bnsLibrary': 'बीएनएस प्रावधान लाइब्रेरी',
    'legal.disclaimerTitle': 'एआई-सहायक कानूनी विश्लेषण',
    'legal.disclaimerText': 'अधिकृत अधिकारी समीक्षा आवश्यक है। अंतिम कानूनी निर्णय नहीं है।',
    'legal.clickToView': 'पूर्ण प्रावधान देखने के लिए क्लिक करें',
    'legal.relevance': 'प्रासंगिकता',
    'legal.keyElements': 'मुख्य तत्व',
  },
  or: {
    // Brand & Header
    'brand.name': 'S.I.R.I.S',
    'brand.tagline': 'ଓଡ଼ିଶା ପୋଲିସ ଗୁପ୍ତଚର ବିଭାଗ',
    'header.station': 'ଥାନା',
    'header.stateCommand': 'ଓଡ଼ିଶା ପୋଲିସ · ରାଜ୍ୟ କମାଣ୍ଡ',
    'header.engineRunning': 'ଇଣ୍ଟେଲିଜେନ୍ସ ଇଞ୍ଜିନ ଚାଲୁଅଛି...',
    'header.newIntel': 'ନୂତନ ଗୁପ୍ତଚର ସୂଚନା ମିଳିଛି:',
    'header.viewDetails': 'ବିବରଣୀ ଦେଖନ୍ତୁ',
    'header.language': 'ଭାଷା',

    // Sidebar
    'nav.section.myDesk': 'ମୋର ଡେସ୍କ',
    'nav.section.investigate': 'ତଦନ୍ତ କରନ୍ତୁ',
    'nav.section.intelligence': 'ଇଣ୍ଟେଲିଜେନ୍ସ',
    'nav.section.assistance': 'ସହାୟତା',
    'nav.section.reports': 'ରିପୋର୍ଟ',
    'nav.section.stateCommand': 'ରାଜ୍ୟ କମାଣ୍ଡ',
    'nav.section.policeAdmin': 'ପୋଲିସ ପ୍ରଶାସନ',
    'nav.section.caseIntel': 'ମାମଲା ଇଣ୍ଟେଲିଜେନ୍ସ',
    'nav.section.networkIntel': 'ନେଟୱାର୍କ ଇଣ୍ଟେଲିଜେନ୍ସ',
    'nav.section.operations': 'କାର୍ଯ୍ୟାନୁଷ୍ଠାନ',
    'nav.section.system': 'ସିଷ୍ଟମ',

    'nav.dashboard': 'ଡ୍ୟାସବୋର୍ଡ',
    'nav.commandCenter': 'କମାଣ୍ଡ ସେଣ୍ଟର',
    'nav.myInvestigations': 'ମୋର ତଦନ୍ତ ସମୂହ',
    'nav.accessRequests': 'ଅନୁମତି ଅନୁରୋଧ',
    'nav.registerFir': 'ଏତଲା (FIR) ପଞ୍ଜୀକରଣ',
    'nav.evidenceVault': 'ପ୍ରମାଣ ଭଣ୍ଡାର',
    'nav.caseSearch': 'ମାମଲା ଖୋଜନ୍ତୁ',
    'nav.allCases': 'ସମସ୍ତ ମାମଲା',
    'nav.networkExplorer': 'ନେଟୱାର୍କ ଏକ୍ସପ୍ଲୋରର',
    'nav.crimeIntelligence': 'ଅପରାଧ ଇଣ୍ଟେଲିଜେନ୍ସ',
    'nav.legalIntelligence': 'ଆଇନଗତ ଇଣ୍ଟେଲିଜେନ୍ସ',
    'nav.aiAssistant': 'AI ସହାୟକ',
    'nav.caseReports': 'ମାମଲା ରିପୋର୍ଟ',
    'nav.policeStations': 'ପୋଲିସ ଥାନା',
    'nav.officers': 'ଅଧିକାରୀଗଣ',
    'nav.monthlyReports': 'ମାସିକ ଅପରାଧ ରିପୋର୍ଟ',
    'nav.notifications': 'ବିଜ୍ଞପ୍ତି',
    'nav.profile': 'ପ୍ରୋଫାଇଲ',

    // Dashboard UI
    'dashboard.title': 'ଡ୍ୟାସବୋର୍ଡ',
    'dashboard.subtitle': 'ତଦନ୍ତ ଏବଂ ଗୁପ୍ତଚର ତଥ୍ୟର ସଦ୍ୟତମ ବିବରଣୀ',
    'dashboard.filters': 'ଫିଲ୍ଟର',
    'dashboard.resetFilters': 'ଫିଲ୍ଟର ରିସେଟ କରନ୍ତୁ',
    'dashboard.district': 'ଜିଲ୍ଲା',
    'dashboard.category': 'ଅପରାଧ ବର୍ଗ',
    'dashboard.priority': 'ପ୍ରାଥମିକତା',
    'dashboard.activeCases': 'ସକ୍ରିୟ ମାମଲା',
    'dashboard.pendingCases': 'ବିଚାରାଧୀନ ମାମଲା',
    'dashboard.highPriority': 'ଉଚ୍ଚ ପ୍ରାଥମିକତା',
    'dashboard.intelAlerts': 'ଇଣ୍ଟେଲିଜେନ୍ସ ସତର୍କତା',
    'dashboard.totalFirs': 'ମୋଟ FIR',
    'dashboard.casesClosed': 'ସମାପ୍ତ ମାମଲା',
    'dashboard.overdueWork': 'ବାକି ଥିବା କାର୍ଯ୍ୟ',
    'dashboard.activeOfficers': 'ସକ୍ରିୟ ଅଧିକାରୀ',
    'dashboard.firTrend': 'FIR ପଞ୍ଜୀକରଣ ଧାରା',
    'dashboard.casesByCrime': 'ଅପରାଧ ବର୍ଗ ଅନୁଯାୟୀ ମାମଲା',
    'dashboard.crimeHotspots': 'ଅପରାଧ ହଟସ୍ପଟ (ଏହି ମାସ)',
    'dashboard.crossStation': 'କ୍ରସ-ଷ୍ଟେସନ ସଂଯୋଗ',
    'dashboard.activeInvestigations': 'ସକ୍ରିୟ ତଦନ୍ତ',
    'dashboard.intelligenceAlerts': 'ଗୁପ୍ତଚର ସତର୍କତା',
    'dashboard.resolved': 'ସମାଧାନ ହୋଇଛି',
    'dashboard.pending': 'ବାକି ଅଛି',
    'dashboard.closureRate': 'ସମାଧାନ ହାର',
    'dashboard.viewAll': 'ସମସ୍ତ ଦେଖନ୍ତୁ',
    'dashboard.openCase': 'ମାମଲା କାର୍ଯ୍ୟକ୍ଷେତ୍ର ଖୋଲନ୍ତୁ',
    'dashboard.caseId': 'ମାମଲା ID',
    'dashboard.caseTitle': 'ମାମଲା ଶୀର୍ଷକ',
    'dashboard.officer': 'ତଦନ୍ତକାରୀ ଅଧିକାରୀ',
    'dashboard.risk': 'ଝୁଙ୍କି',
    'dashboard.daysActive': 'ସକ୍ରିୟ ଦିନ',
    'dashboard.progress': 'ଅଗ୍ରଗତି',
    'dashboard.highStrength': 'ଉଚ୍ଚ ଶକ୍ତି',
    'dashboard.mediumStrength': 'ମଧ୍ୟମ',
    'dashboard.lowStrength': 'କମ',
    'dashboard.days': 'ଦିନ',
    'dashboard.thisMonth': 'ଏହି ମାସ',
    'dashboard.last30Days': 'ଗତ ୩୦ ଦିନ',
    'dashboard.thisQuarter': 'ଏହି ତ୍ରୟମାସ',

    // Categories
    'cat.cyber': 'ସାଇବର ଅପରାଧ',
    'cat.financial': 'ଆର୍ଥିକ ଠକେଇ',
    'cat.theft': 'ଚୋରି',
    'cat.extortion': 'ଜବରଦସ୍ତି ଆଦାୟ',
    'cat.assault': 'ଆକ୍ରମଣ',
    'cat.other': 'ଅନ୍ୟାନ୍ୟ ଅପରାଧ',

    'btn.runAiAnalysis': 'AI ବିଶ୍ଳେଷଣ ଚଲାନ୍ତୁ',
    'btn.confirmCreateCase': 'ମାମଲା ସୃଷ୍ଟି କରନ୍ତୁ',
    'btn.processEvidence': 'ପ୍ରମାଣ ବିଶ୍ଳେଷଣ କରନ୍ତୁ',
    'btn.requestAccess': 'ଅନୁମତି ଅନୁରୋଧ କରନ୍ତୁ',
    'btn.search': 'ସନ୍ଧାନ',
    'btn.reset': 'ରିସେଟ',
    'btn.downloadPdf': 'PDF ଡାଉନଲୋଡ',
    'btn.cancel': 'ବାତିଲ',
    'btn.close': 'ବନ୍ଦ କରନ୍ତୁ',

    // AIRA & Voice Intelligence
    'aira.greeting': 'ନମସ୍କାର ଇନ୍ସପେକ୍ଟର। ମୁଁ AIRA, ଆପଣଙ୍କ ଭଏସ୍ ଇଣ୍ଟେଲିଜେନ୍ସ ସାଥୀ।',
    'aira.listening': 'ଶୁଣିବା ସକ୍ରିୟ ଅଛି',
    'aira.analyzing': 'AIRA ବିଶ୍ଳେଷଣ କରୁଛି',
    'aira.tapToSpeak': 'କହିବା ପାଇଁ ଟ୍ୟାପ୍ କରନ୍ତୁ',
    'aira.audioPlaying': 'ଉତ୍ତର କହୁଛି...',
    'aira.playAudio': 'ସ୍ୱର ଶୁଣନ୍ତୁ',
    'aira.replayAudio': 'ପୁଣି ଶୁଣନ୍ତୁ',
    'aira.pauseAudio': 'ବିରାମ',
    'aira.stopAudio': 'ବନ୍ଦ କରନ୍ତୁ',

    // Legal Intelligence
    'legal.title': 'ଆଇନଗତ ଇଣ୍ଟେଲିଜେନ୍ସ (BNS)',
    'legal.applicableProvisions': 'ପ୍ରଯୁଜ୍ୟ ଧାରା ସମୂହ',
    'legal.bnsLibrary': 'BNS ଧାରା ତାଲିକା',
    'legal.disclaimerTitle': 'AI ଆଇନଗତ ସହାୟତା',
    'legal.disclaimerText': 'ଅଧିକାରୀଙ୍କ ଦ୍ୱାରା ଯାଞ୍ଚ ଆବଶ୍ୟକ। ଏହା ଚୂଡ଼ାନ୍ତ ଆଇନ ନିର୍ଦ୍ଧାରଣ ନୁହେଁ।',
    'legal.clickToView': 'ପୂର୍ଣ୍ଣ ବିବରଣୀ ପାଇଁ କ୍ଲିକ୍ କରନ୍ତୁ',
    'legal.relevance': 'ପ୍ରାସଙ୍ଗିକତା',
    'legal.keyElements': 'ମୁଖ୍ୟ ଉପାଦାନ',
  },
  bn: {
    'brand.name': 'S.I.R.I.S',
    'brand.tagline': 'ওড়িশা পুলিশ ইন্টেলিজেন্স',
    'header.station': 'থানা',
    'header.stateCommand': 'ওড়িশা পুলিশ · রাজ্য কমান্ড',
    'header.engineRunning': 'ইন্টেলিজেন্স ইঞ্জিন সক্রিয়...',
    'header.newIntel': 'নতুন গোয়েন্দা তথ্য পাওয়া গেছে:',
    'header.viewDetails': 'বিবরণ দেখুন',
    'header.language': 'ভাষা',

    'nav.section.myDesk': 'আমার ডেস্ক',
    'nav.section.investigate': 'তদন্ত',
    'nav.section.intelligence': 'ইন্টেলিজেন্স',
    'nav.section.assistance': 'সহায়তা',
    'nav.section.reports': 'রিপোর্ট',
    'nav.section.stateCommand': 'রাজ্য কমান্ড',
    'nav.section.policeAdmin': 'পুলিশ প্রশাসন',
    'nav.section.caseIntel': 'মামলা গোয়েন্দা তথ্য',
    'nav.section.networkIntel': 'নেটওয়ার্ক ইন্টেলিজেন্স',
    'nav.section.operations': 'অপারেশনস',
    'nav.section.system': 'সিস্টেম',

    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.commandCenter': 'কমান্ড সেন্টার',
    'nav.myInvestigations': 'আমার তদন্তসমূহ',
    'nav.accessRequests': 'অ্যাক্সেস অনুরোধ',
    'nav.registerFir': 'এফআইআর নথিবদ্ধ করুন',
    'nav.evidenceVault': 'প্রমাণ ভল্ট',
    'nav.caseSearch': 'মামলা অনুসন্ধান',
    'nav.allCases': 'সকল মামলা',
    'nav.networkExplorer': 'নেটওয়ার্ক এক্সপ্লোরার',
    'nav.crimeIntelligence': 'ক্রাইম ইন্টেলিজেন্স',
    'nav.legalIntelligence': 'আইনি ইন্টেলিজেন্স',
    'nav.aiAssistant': 'এআই সহকারী',
    'nav.caseReports': 'মামলার রিপোর্ট',
    'nav.policeStations': 'পুলিশ স্টেশন',
    'nav.officers': 'কর্মকর্তাবৃন্দ',
    'nav.monthlyReports': 'মাসিক অপরাধ রিপোর্ট',
    'nav.notifications': 'বিজ্ঞপ্তি',
    'nav.profile': 'প্রোফাইল',

    'dashboard.title': 'ড্যাশবোর্ড',
    'dashboard.subtitle': 'তদন্ত ও গোয়েন্দা তথ্যের রিয়েল-টাইম ওভারভিউ',
    'dashboard.filters': 'ফিল্টার',
    'dashboard.resetFilters': 'ফিল্টার রিসেট',
    'dashboard.district': 'জেলা',
    'dashboard.category': 'অপরাধের ধরন',
    'dashboard.priority': 'অগ্রাধিকার',
    'dashboard.activeCases': 'সক্রিয় মামলা',
    'dashboard.pendingCases': 'বিচারাধীন মামলা',
    'dashboard.highPriority': 'উচ্চ অগ্রাধিকার',
    'dashboard.intelAlerts': 'গোয়েন্দা সতর্কতা',
    'dashboard.totalFirs': 'মোট এফআইআর',
    'dashboard.casesClosed': 'নিষ্পত্তি মামলা',
    'dashboard.overdueWork': 'বকেয়া কাজ',
    'dashboard.activeOfficers': 'কর্মরত কর্মকর্তা',
    'dashboard.firTrend': 'এফআইআর প্রবণতা',
    'dashboard.casesByCrime': 'অপরাধ ভিত্তিক মামলা',
    'dashboard.crimeHotspots': 'ক্রাইম হটস্পট (চলতি মাস)',
    'dashboard.crossStation': 'ক্রস-স্টেশন সংযোগ',
    'dashboard.activeInvestigations': 'সক্রিয় তদন্ত',
    'dashboard.intelligenceAlerts': 'গোয়েন্দা সতর্কতা',
    'dashboard.resolved': 'সমাধানকৃত',
    'dashboard.pending': 'বকেয়া',
    'dashboard.closureRate': 'নিষ্পত্তির হার',
    'dashboard.viewAll': 'সব দেখুন',
    'dashboard.openCase': 'মামলার ওয়ার্কস্পেস খুলুন',
    'dashboard.caseId': 'মামলা নং',
    'dashboard.caseTitle': 'মামলার শিরোনাম',
    'dashboard.officer': 'তদন্তকারী কর্মকর্তা',
    'dashboard.risk': 'ঝুঁকি',
    'dashboard.daysActive': 'সক্রিয় দিন',
    'dashboard.progress': 'অগ্রগতি',
    'dashboard.highStrength': 'উচ্চ মাত্রা',
    'dashboard.mediumStrength': 'মাঝারি',
    'dashboard.lowStrength': 'কম',
    'dashboard.days': 'দিন',
    'dashboard.thisMonth': 'চলতি মাস',
    'dashboard.last30Days': 'গত ৩০ দিন',
    'dashboard.thisQuarter': 'চলতি ত্রৈমাসিক',

    'cat.cyber': 'সাইবার অপরাধ',
    'cat.financial': 'আর্থিক জালিয়াতি',
    'cat.theft': 'চুরি',
    'cat.extortion': 'তোলাবাজি',
    'cat.assault': 'আক্রমণ',
    'cat.other': 'অন্যান্য অপরাধ',

    'btn.runAiAnalysis': 'এআই বিশ্লেষণ চালান',
    'btn.confirmCreateCase': 'নিশ্চিত করুন এবং মামলা তৈরি করুন',
    'btn.processEvidence': 'প্রমাণ প্রক্রিয়া করুন',
    'btn.requestAccess': 'অ্যাক্সেসের আবেদন করুন',
    'btn.search': 'অনুসন্ধান',
    'btn.reset': 'রিসেট',
    'btn.downloadPdf': 'পিডিএফ ডাউনলোড',
    'btn.cancel': 'বাতিল',
    'btn.close': 'বন্ধ করুন',

    // AIRA & Voice Intelligence
    'aira.greeting': 'নমস্কার পরিদর্শক। আমি আয়রা (AIRA), আপনার ভয়েস ইন্টেলিজেন্স সহকারী।',
    'aira.listening': 'শ্রবণ সক্রিয় আছে',
    'aira.analyzing': 'আয়রা বিশ্লেষণ করছে',
    'aira.tapToSpeak': 'বলতে ট্যাপ করুন',
    'aira.audioPlaying': 'উত্তর বলছে...',
    'aira.playAudio': 'কণ্ঠ শুনুন',
    'aira.replayAudio': 'আবার শুনুন',
    'aira.pauseAudio': 'বিরতি',
    'aira.stopAudio': 'বন্ধ করুন',

    // Legal Intelligence
    'legal.title': 'আইনি ইন্টেলিজেন্স (BNS)',
    'legal.applicableProvisions': 'প্রযোজ্য ধারা সমূহ',
    'legal.bnsLibrary': 'বিএনএস ধারা লাইব্রেরি',
    'legal.disclaimerTitle': 'এআই আইনি সহায়তা',
    'legal.disclaimerText': 'অনুমোদিত কর্মকর্তার পর্যালোচনা প্রয়োজন। এটি চূড়ান্ত আইনি সিদ্ধান্ত নয়।',
    'legal.clickToView': 'সম্পূর্ণ ধারা দেখতে ক্লিক করুন',
    'legal.relevance': 'প্রাসঙ্গিকতা',
    'legal.keyElements': 'মূল উপাদান',
  },
  te: {
    'brand.name': 'S.I.R.I.S',
    'brand.tagline': 'ఒడిశా పోలీస్ ఇంటెలిజెన్స్',
    'header.station': 'స్టేషన్',
    'header.stateCommand': 'ఒడిశా పోలీస్ · రాష్ట్ర కమాండ్',
    'header.engineRunning': 'ఇంటెలిజెన్స్ ఇంజిన్ రన్ అవుతోంది...',
    'header.newIntel': 'కొత్త ఇంటెలిజెన్స్ కనుగొనబడింది:',
    'header.viewDetails': 'వివరాలు చూడండి',
    'header.language': 'భాష',

    'nav.section.myDesk': 'నా డెస్క్',
    'nav.section.investigate': 'పరిశోధించండి',
    'nav.section.intelligence': 'ఇంటెలిజెన్స్',
    'nav.section.assistance': 'సహాయం',
    'nav.section.reports': 'నివేదికలు',
    'nav.section.stateCommand': 'రాష్ట్ర కమాండ్',
    'nav.section.policeAdmin': 'పోలీస్ పరిపాలన',
    'nav.section.caseIntel': 'కేస్ ఇంటెలిజెన్స్',
    'nav.section.networkIntel': 'నెట్‌వర్క్ ఇంటెలిజెన్స్',
    'nav.section.operations': 'కార్యకలాపాలు',
    'nav.section.system': 'సిస్టమ్',

    'nav.dashboard': 'డాష్‌బోర్డ్',
    'nav.commandCenter': 'కమాండ్ సెంటర్',
    'nav.myInvestigations': 'నా దర్యాప్తులు',
    'nav.accessRequests': 'యాక్సెస్ అభ్యర్థనలు',
    'nav.registerFir': 'ఎఫ్ఐఆర్ నమోదు',
    'nav.evidenceVault': 'సాక్ష్యాల వాల్ట్',
    'nav.caseSearch': 'కేస్ శోధన',
    'nav.allCases': 'అన్ని కేసులు',
    'nav.networkExplorer': 'నెట్‌వర్క్ ఎక్స్‌ప్లోరర్',
    'nav.crimeIntelligence': 'క్రైమ్ ఇంటెలిజెన్స్',
    'nav.legalIntelligence': 'లీగల్ ఇంటెలిజెన్స్',
    'nav.aiAssistant': 'AI అసిస్టెంట్',
    'nav.caseReports': 'కేస్ రిపోర్ట్‌లు',
    'nav.policeStations': 'పోలీస్ స్టేషన్లు',
    'nav.officers': 'అధికారులు',
    'nav.monthlyReports': 'నెలవారీ క్రైమ్ రిపోర్ట్‌లు',
    'nav.notifications': 'నోటిఫికేషన్‌లు',
    'nav.profile': 'ప్రొఫైల్',

    'dashboard.title': 'డాష్‌బోర్డ్',
    'dashboard.subtitle': 'దర్యాప్తులు మరియు ఇంటెలిజెన్స్ యొక్క నిజ-సమయ వీక్షణ',
    'dashboard.filters': 'ఫిల్టర్లు',
    'dashboard.resetFilters': 'రీసెట్ ఫిల్టర్లు',
    'dashboard.district': 'జిల్లా',
    'dashboard.category': 'నేర విభాగం',
    'dashboard.priority': 'ప్రాధాన్యత',
    'dashboard.activeCases': 'క్రియాశీల కేసులు',
    'dashboard.pendingCases': 'పెండింగ్ కేసులు',
    'dashboard.highPriority': 'అధిక ప్రాధాన్యత',
    'dashboard.intelAlerts': 'ఇంటెల్ హెచ్చరికలు',
    'dashboard.totalFirs': 'మొత్తం ఎఫ్ఐఆర్‌లు',
    'dashboard.casesClosed': 'పరిష్కరించబడిన కేసులు',
    'dashboard.overdueWork': 'గడువు ముగిసిన పనులు',
    'dashboard.activeOfficers': 'క్రియాశీల అధికారులు',
    'dashboard.firTrend': 'ఎఫ్ఐఆర్ ధోరణి',
    'dashboard.casesByCrime': 'నేర వర్గం ప్రకారం కేసులు',
    'dashboard.crimeHotspots': 'క్రైమ్ హాట్‌స్పాట్‌లు (ఈ నెల)',
    'dashboard.crossStation': 'క్రాస్-స్టేషన్ లింకులు',
    'dashboard.activeInvestigations': 'క్రియాశీల పరిశోధనలు',
    'dashboard.intelligenceAlerts': 'ఇంటెలిజెన్స్ హెచ్చరికలు',
    'dashboard.resolved': 'పరిష్కరించబడినవి',
    'dashboard.pending': 'పెండింగ్',
    'dashboard.closureRate': 'పరిష్కార రేటు',
    'dashboard.viewAll': 'అన్నీ చూడండి',
    'dashboard.openCase': 'కేసు వర్క్‌స్పేస్ తెరవండి',
    'dashboard.caseId': 'కేస్ ID',
    'dashboard.caseTitle': 'కేస్ శీర్షిక',
    'dashboard.officer': 'విచారణ అధికారి',
    'dashboard.risk': 'రిస్క్',
    'dashboard.daysActive': 'క్రియాశీల రోజులు',
    'dashboard.progress': 'పురోగతి',
    'dashboard.highStrength': 'అధిక తీవ్రత',
    'dashboard.mediumStrength': 'మధ్యస్థం',
    'dashboard.lowStrength': 'తక్కువ',
    'dashboard.days': 'రోజులు',
    'dashboard.thisMonth': 'ఈ నెల',
    'dashboard.last30Days': 'గత 30 రోజులు',
    'dashboard.thisQuarter': 'ఈ త్రైమాసికం',

    'cat.cyber': 'సైబర్ నేరం',
    'cat.financial': 'ఆర్థిక మోసం',
    'cat.theft': 'దొంగతనం',
    'cat.extortion': 'దోపిడీ',
    'cat.assault': 'దాడి',
    'cat.other': 'ఇతర నేరాలు',

    'btn.runAiAnalysis': 'AI విశ్లేషణను అమలు చేయండి',
    'btn.confirmCreateCase': 'నిర్ధారించి కేస్ సృష్టించండి',
    'btn.processEvidence': 'సాక్ష్యాన్ని ప్రాసెస్ చేయండి',
    'btn.requestAccess': 'యాక్సెస్ అభ్యర్థించండి',
    'btn.search': 'శోధన',
    'btn.reset': 'రీసెట్',
    'btn.downloadPdf': 'PDF డౌన్‌లోడ్',
    'btn.cancel': 'రద్దు చేయండి',
    'btn.close': 'మూసివేయి',

    // AIRA & Voice Intelligence
    'aira.greeting': 'నమస్కారం ఇన్‌స్పెక్టర్. నేను ఐరా (AIRA), మీ వాయిస్ ఇంటెలిజెన్స్ అసిస్టెంట్.',
    'aira.listening': 'వినడం సక్రియంగా ఉంది',
    'aira.analyzing': 'ఐరా విశ్లేషిస్తోంది',
    'aira.tapToSpeak': 'మాట్లాడటానికి ట్యాప్ చేయండి',
    'aira.audioPlaying': 'సమాధానం చెబుతోంది...',
    'aira.playAudio': 'వాయిస్ వినండి',
    'aira.replayAudio': 'మళ్ళీ వినండి',
    'aira.pauseAudio': 'పాజ్ చేయండి',
    'aira.stopAudio': 'ఆపండి',

    // Legal Intelligence
    'legal.title': 'లీగల్ ఇంటెలిజెన్స్ (BNS)',
    'legal.applicableProvisions': 'వర్తించే నిబంధనలు',
    'legal.bnsLibrary': 'BNS నిబంధనల లైబ్రరీ',
    'legal.disclaimerTitle': 'AI సహాయక న్యాయ విశ్లేషణ',
    'legal.disclaimerText': 'అధికారిక సమీక్ష అవసరం. ఇది తుది చట్టపరమైన తీర్పు కాదు.',
    'legal.clickToView': 'పూర్తి వివరాల కోసం క్లిక్ చేయండి',
    'legal.relevance': 'ప్రాముఖ్యత',
    'legal.keyElements': 'ముఖ్య అంశాలు',
  },
  ta: {
    'brand.name': 'S.I.R.I.S',
    'brand.tagline': 'ஒடிசா காவல் நுண்ணறிவு பிரிவு',
    'header.station': 'காவல் நிலையம்',
    'header.stateCommand': 'ஒடிசா காவல்துறை · மாநில கட்டளை',
    'header.engineRunning': 'நுண்ணறிவு இயந்திரம் இயங்குகிறது...',
    'header.newIntel': 'புதிய உளவுத் தகவல் கண்டறியப்பட்டது:',
    'header.viewDetails': 'விவரங்களைக் காண்க',
    'header.language': 'மொழி',

    'nav.section.myDesk': 'என் மேசை',
    'nav.section.investigate': 'விசாரணை',
    'nav.section.intelligence': 'நுண்ணறிவு',
    'nav.section.assistance': 'உதவி',
    'nav.section.reports': 'அறிக்கைகள்',
    'nav.section.stateCommand': 'மாநில கட்டளை',
    'nav.section.policeAdmin': 'காவல் நிர்வாகம்',
    'nav.section.caseIntel': 'வழக்கு நுண்ணறிவு',
    'nav.section.networkIntel': 'நெட்வொர்க் உளவு',
    'nav.section.operations': 'செயல்பாடுகள்',
    'nav.section.system': 'அமைப்பு',

    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.commandCenter': 'கட்டளை மையம்',
    'nav.myInvestigations': 'என் விசாரணைகள்',
    'nav.accessRequests': 'அணுகல் கோரிக்கைகள்',
    'nav.registerFir': 'முதல் தகவல் அறிக்கை (FIR)',
    'nav.evidenceVault': 'ஆதார பெட்டகம்',
    'nav.caseSearch': 'வழக்கு தேடல்',
    'nav.allCases': 'அனைத்து வழக்குகள்',
    'nav.networkExplorer': 'நெட்வொர்க் எக்ஸ்ப்ளோரர்',
    'nav.crimeIntelligence': 'குற்ற நுண்ணறிவு',
    'nav.legalIntelligence': 'சட்ட நுண்ணறிவு',
    'nav.aiAssistant': 'AI உதவியாளர்',
    'nav.caseReports': 'வழக்கு அறிக்கைகள்',
    'nav.policeStations': 'காவல் நிலையங்கள்',
    'nav.officers': 'அதிகாரிகள்',
    'nav.monthlyReports': 'மாதாந்திர குற்ற அறிக்கை',
    'nav.notifications': 'அறிவிப்புகள்',
    'nav.profile': 'சுயவிவரம்',

    'dashboard.title': 'டாஷ்போர்டு',
    'dashboard.subtitle': 'விசாரணைகள் மற்றும் நுண்ணறிவின் நிகழ்நேர பார்வை',
    'dashboard.filters': 'வடிகட்டிகள்',
    'dashboard.resetFilters': 'மீட்டமைக்க',
    'dashboard.district': 'மாவட்டம்',
    'dashboard.category': 'குற்றப் பிரிவு',
    'dashboard.priority': 'முன்னுரிமை',
    'dashboard.activeCases': 'செயலில் உள்ள வழக்குகள்',
    'dashboard.pendingCases': 'நிலுவையில் உள்ள வழக்குகள்',
    'dashboard.highPriority': 'உயர் முன்னுரிமை',
    'dashboard.intelAlerts': 'நுண்ணறிவு எச்சரிக்கைகள்',
    'dashboard.totalFirs': 'மொத்த எஃப்.ஐ.ஆர்',
    'dashboard.casesClosed': 'முடிக்கப்பட்ட வழக்குகள்',
    'dashboard.overdueWork': 'தாமதமான பணிகள்',
    'dashboard.activeOfficers': 'செயலில் உள்ள அதிகாரிகள்',
    'dashboard.firTrend': 'எஃப்.ஐ.ஆர் போக்கு',
    'dashboard.casesByCrime': 'குற்ற வகை வாரியாக வழக்குகள்',
    'dashboard.crimeHotspots': 'குற்ற ஹாட்ஸ்பாட்கள் (இந்த மாதம்)',
    'dashboard.crossStation': 'நிலையங்களுக்கு இடையேயான இணைப்புகள்',
    'dashboard.activeInvestigations': 'செயலில் உள்ள விசாரணைகள்',
    'dashboard.intelligenceAlerts': 'உளவு எச்சரிக்கைகள்',
    'dashboard.resolved': 'தீர்க்கப்பட்டது',
    'dashboard.pending': 'நிலுவையில்',
    'dashboard.closureRate': 'தீர்வு விகிதம்',
    'dashboard.viewAll': 'அனைத்தையும் காண்க',
    'dashboard.openCase': 'வழக்கு பணிப்பகுதியைத் திற',
    'dashboard.caseId': 'வழக்கு எண்',
    'dashboard.caseTitle': 'வழக்கு தலைப்பு',
    'dashboard.officer': 'விசாரணை அதிகாரி',
    'dashboard.risk': 'ஆபத்து',
    'dashboard.daysActive': 'செயலில் உள்ள நாட்கள்',
    'dashboard.progress': 'முன்னேற்றம்',
    'dashboard.highStrength': 'உயர் வலிமை',
    'dashboard.mediumStrength': 'நடுத்தர',
    'dashboard.lowStrength': 'குறைந்த',
    'dashboard.days': 'நாட்கள்',
    'dashboard.thisMonth': 'இந்த மாதம்',
    'dashboard.last30Days': 'கடந்த 30 நாட்கள்',
    'dashboard.thisQuarter': 'இந்த காலாண்டு',

    'cat.cyber': 'சைபர் குற்றம்',
    'cat.financial': 'நிதி மோசடி',
    'cat.theft': 'திருட்டு',
    'cat.extortion': 'பறிமுதல்',
    'cat.assault': 'தாக்குதல்',
    'cat.other': 'பிற குற்றங்கள்',

    'btn.runAiAnalysis': 'AI பகுப்பாய்வு இயக்கு',
    'btn.confirmCreateCase': 'வழக்கை உருவாக்க உறுதிசெய்',
    'btn.processEvidence': 'ஆதாரத்தை பகுப்பாய்வு செய்',
    'btn.requestAccess': 'அணுகல் கோரிக்கை வை',
    'btn.search': 'தேடு',
    'btn.reset': 'மீட்டமை',
    'btn.downloadPdf': 'PDF பதிவிறக்கம்',
    'btn.cancel': 'ரத்து',
    'btn.close': 'மூடு',

    // AIRA & Voice Intelligence
    'aira.greeting': 'வணக்கம் இன்ஸ்பெக்டர். நான் ஐரா (AIRA), உங்கள் குரல் நுண்ணறிவு உதவியாளர்.',
    'aira.listening': 'கேட்கிறது...',
    'aira.analyzing': 'ஐரா பகுப்பாய்வு செய்கிறது',
    'aira.tapToSpeak': 'பேச தட்டவும்',
    'aira.audioPlaying': 'பதிலை ஒலிக்கிறது...',
    'aira.playAudio': 'குரல் இயக்கு',
    'aira.replayAudio': 'மீண்டும் கேள்',
    'aira.pauseAudio': 'இடைநிறுத்து',
    'aira.stopAudio': 'நிறுத்து',

    // Legal Intelligence
    'legal.title': 'சட்ட நுண்ணறிவு (BNS)',
    'legal.applicableProvisions': 'பொருந்தக்கூடிய சட்டப்பிரிவுகள்',
    'legal.bnsLibrary': 'BNS சட்டப்பிரிவு நூலகம்',
    'legal.disclaimerTitle': 'AI சட்ட நுண்ணறிவு',
    'legal.disclaimerText': 'அதிகாரியின் ஆய்வு தேவை. இது இறுதி சட்ட முடிவு அல்ல.',
    'legal.clickToView': 'முழு விவரம் பார்க்க கிளிக் செய்',
    'legal.relevance': 'பொருத்தம்',
    'legal.keyElements': 'முக்கிய கூறுகள்',
  },
  mr: {
    'brand.name': 'S.I.R.I.S',
    'brand.tagline': 'ओडिशा पोलीस इंटेलिजन्स',
    'header.station': 'पोलीस ठाणे',
    'header.stateCommand': 'ओडिशा पोलीस · राज्य कमांड',
    'header.engineRunning': 'इंटेलिजन्स इंजिन चालू आहे...',
    'header.newIntel': 'नवीन गुप्त माहिती सापडली:',
    'header.viewDetails': 'तपशील पहा',
    'header.language': 'भाषा',

    'nav.section.myDesk': 'माझा डेस्क',
    'nav.section.investigate': 'तपास करा',
    'nav.section.intelligence': 'इंटेलिजन्स',
    'nav.section.assistance': 'सहाय्य',
    'nav.section.reports': 'अहवाल',
    'nav.section.stateCommand': 'राज्य कमांड',
    'nav.section.policeAdmin': 'पोलीस प्रशासन',
    'nav.section.caseIntel': 'केस इंटेलिजन्स',
    'nav.section.networkIntel': 'नेटवर्क इंटेलिजन्स',
    'nav.section.operations': 'ऑपरेशन्स',
    'nav.section.system': 'सिस्टम',

    'nav.dashboard': 'डॅशबोर्ड',
    'nav.commandCenter': 'कमांड सेंटर',
    'nav.myInvestigations': 'माझे तपास',
    'nav.accessRequests': 'प्रवेश विनंत्या',
    'nav.registerFir': 'एफआयआर नोंदवा',
    'nav.evidenceVault': 'पुरावा व्हॉल्ट',
    'nav.caseSearch': 'केस शोध',
    'nav.allCases': 'सर्व केसेस',
    'nav.networkExplorer': 'नेटवर्क एक्सप्लोरर',
    'nav.crimeIntelligence': 'गुन्हेगारी इंटेलिजन्स',
    'nav.legalIntelligence': 'कायदेशीर इंटेलिजन्स',
    'nav.aiAssistant': 'एआय सहाय्यक',
    'nav.caseReports': 'केस अहवाल',
    'nav.policeStations': 'पोलीस ठाणी',
    'nav.officers': 'अधिकारी',
    'nav.monthlyReports': 'मासिक गुन्हे अहवाल',
    'nav.notifications': 'सूचना',
    'nav.profile': 'प्रोफाइल',

    'dashboard.title': 'डॅशबोर्ड',
    'dashboard.subtitle': 'तपास आणि गुप्त माहितीचे रिअल-टाइम विहंगावलोकन',
    'dashboard.filters': 'फिल्टर',
    'dashboard.resetFilters': 'फिल्टर रीसेट करा',
    'dashboard.district': 'जिल्हा',
    'dashboard.category': 'गुन्हे श्रेणी',
    'dashboard.priority': 'प्राधान्य',
    'dashboard.activeCases': 'सक्रिय केसेस',
    'dashboard.pendingCases': 'प्रलंबित केसेस',
    'dashboard.highPriority': 'उच्च प्राधान्य',
    'dashboard.intelAlerts': 'इंटेल इशारे',
    'dashboard.totalFirs': 'एकूण एफआयआर',
    'dashboard.casesClosed': 'निकाली काढलेल्या केसेस',
    'dashboard.overdueWork': 'थकबाकी काम',
    'dashboard.activeOfficers': 'सक्रिय अधिकारी',
    'dashboard.firTrend': 'एफआयआर नोंदणी कल',
    'dashboard.casesByCrime': 'गुन्हे श्रेणीनुसार केसेस',
    'dashboard.crimeHotspots': 'क्राइम हॉटस्पॉट्स (या महिन्यात)',
    'dashboard.crossStation': 'क्रॉस-स्टेशन संबंध',
    'dashboard.activeInvestigations': 'सक्रिय तपास',
    'dashboard.intelligenceAlerts': 'गुप्तचर इशारे',
    'dashboard.resolved': 'निकाली काढलेले',
    'dashboard.pending': 'प्रलंबित',
    'dashboard.closureRate': 'निकाली दर',
    'dashboard.viewAll': 'सर्व पहा',
    'dashboard.openCase': 'केस वर्कस्पेस उघडा',
    'dashboard.caseId': 'केस आयडी',
    'dashboard.caseTitle': 'केस शीर्षक',
    'dashboard.officer': 'तपास अधिकारी',
    'dashboard.risk': 'जोखीम',
    'dashboard.daysActive': 'सक्रिय दिवस',
    'dashboard.progress': 'प्रगती',
    'dashboard.highStrength': 'उच्च तीव्रता',
    'dashboard.mediumStrength': 'मध्यम',
    'dashboard.lowStrength': 'कमी',
    'dashboard.days': 'दिवस',
    'dashboard.thisMonth': 'हा महिना',
    'dashboard.last30Days': 'मागील ३० दिवस',
    'dashboard.thisQuarter': 'हा त्रैमासिक',

    'cat.cyber': 'सायबर गुन्हे',
    'cat.financial': 'आर्थिक फसवणूक',
    'cat.theft': 'चोरी',
    'cat.extortion': 'खंडणी',
    'cat.assault': 'हल्ला',
    'cat.other': 'इतर गुन्हे',

    'btn.runAiAnalysis': 'एआय विश्लेषण चालवा',
    'btn.confirmCreateCase': 'केस तयार करण्याची पुष्टी करा',
    'btn.processEvidence': 'पुरावा प्रक्रिया करा',
    'btn.requestAccess': 'प्रवेशाची विनंती करा',
    'btn.search': 'शोधा',
    'btn.reset': 'रीसेट',
    'btn.downloadPdf': 'पीडीएफ डाउनलोड',
    'btn.cancel': 'रद्द करा',
    'btn.close': 'बंद करा',

    // AIRA & Voice Intelligence
    'aira.greeting': 'नमस्कार इन्स्पेक्टर. मी आयरा (AIRA), तुमची व्हॉइस इंटेलिजन्स साथीदार.',
    'aira.listening': 'ऐकणे सक्रिय आहे',
    'aira.analyzing': 'आयरा विश्लेषण करत आहे',
    'aira.tapToSpeak': 'बोलण्यासाठी टॅप करा',
    'aira.audioPlaying': 'उत्तर वाचत आहे...',
    'aira.playAudio': 'आवाज ऐका',
    'aira.replayAudio': 'पुन्हा ऐका',
    'aira.pauseAudio': 'थांबवा',
    'aira.stopAudio': 'बंद करा',

    // Legal Intelligence
    'legal.title': 'कायदेशीर इंटेलिजन्स (BNS)',
    'legal.applicableProvisions': 'लागू कलमे',
    'legal.bnsLibrary': 'BNS कलम ग्रंथालय',
    'legal.disclaimerTitle': 'एआय कायदेशीर सहाय्य',
    'legal.disclaimerText': 'अधिकृत अधिकाऱ्याचे पुनरावलोकन आवश्यक. हा अंतिम कायदेशीर निर्णय नाही.',
    'legal.clickToView': 'पूर्ण कलम पाहण्यासाठी क्लिक करा',
    'legal.relevance': 'सुसंगतता',
    'legal.keyElements': 'मुख्य घटक',
  }
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, defaultText?: string) => string;
  languages: LanguageOption[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLangState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('crimelens-lang') as LanguageCode;
    return saved && TRANSLATIONS[saved] ? saved : 'en';
  });

  const setLanguage = (lang: LanguageCode) => {
    setLangState(lang);
    localStorage.setItem('crimelens-lang', lang);
  };

  const t = (key: string, defaultText?: string): string => {
    const langDict = TRANSLATIONS[language];
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    const enDict = TRANSLATIONS['en'];
    if (enDict && enDict[key]) {
      return enDict[key];
    }
    return defaultText || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages: SUPPORTED_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};
