import React from 'react';
import { Scale, FileText, Search, ShieldAlert, BookOpen } from 'lucide-react';

export function LegalIntelligence() {
  return (
    <div className="space-y-6 animate-fade-in max-w-7xl mx-auto">
      <div>
        <h2 className="text-2xl font-bold text-text font-display flex items-center gap-2">
          <Scale className="text-brand" /> Legal Intelligence
        </h2>
        <p className="text-sm text-text-dim mt-1">AI-assisted analysis of Bharatiya Nyaya Sanhita (BNS) and BNSS procedures.</p>
      </div>

      <div className="bg-warning/10 border border-warning/30 p-4 rounded-xl flex items-start gap-3">
        <ShieldAlert className="text-warning shrink-0 mt-0.5" size={20} />
        <div>
          <h4 className="text-sm font-bold text-warning uppercase tracking-wider mb-1">AI-ASSISTED — REQUIRES AUTHORIZED OFFICER REVIEW</h4>
          <p className="text-xs text-text-dim">Legal intelligence is generated by analyzing case patterns against BNS provisions. It does not constitute final legal authority. All charges must be reviewed by the investigating officer before filing the charge sheet.</p>
        </div>
      </div>

      <div className="grid md:grid-cols-3 gap-6">
        <div className="md:col-span-1 space-y-4">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-text-dim" size={16} />
            <input 
              type="text" 
              placeholder="Search BNS provisions..." 
              className="w-full bg-surface border border-border-soft rounded-lg pl-9 pr-4 py-3 text-sm text-text focus:border-brand outline-none"
            />
          </div>
          
          <div className="glass rounded-xl p-4">
            <h3 className="font-bold text-sm uppercase tracking-wider text-text-dim mb-4 border-b border-border-soft pb-2">Common Provisions</h3>
            <ul className="space-y-2">
              <li className="text-sm text-text hover:text-brand cursor-pointer p-2 rounded hover:bg-surface-hover transition-colors">BNS Sec 303 (Theft)</li>
              <li className="text-sm text-text hover:text-brand cursor-pointer p-2 rounded hover:bg-surface-hover transition-colors bg-surface-hover border-l-2 border-brand">BNS Sec 309 (Robbery)</li>
              <li className="text-sm text-text hover:text-brand cursor-pointer p-2 rounded hover:bg-surface-hover transition-colors">BNS Sec 316 (Criminal Breach of Trust)</li>
              <li className="text-sm text-text hover:text-brand cursor-pointer p-2 rounded hover:bg-surface-hover transition-colors">BNS Sec 336 (Forgery)</li>
            </ul>
          </div>
        </div>

        <div className="md:col-span-2 space-y-6">
          <div className="glass rounded-xl p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="h-10 w-10 rounded bg-brand/10 text-brand flex items-center justify-center font-bold text-lg border border-brand/20">309</div>
              <div>
                <h3 className="text-xl font-bold text-text">BNS Section 309</h3>
                <p className="text-sm text-text-dim">Robbery</p>
              </div>
            </div>
            
            <div className="space-y-4">
              <div>
                <h4 className="text-xs font-bold uppercase tracking-wider text-text-faint mb-2 flex items-center gap-2"><BookOpen size={14} /> Provision Text</h4>
                <div className="bg-surface-2 p-4 rounded-lg text-sm text-text leading-relaxed border border-border-soft">
                  (1) In all robbery there is either theft or extortion.
                  (2) Theft is "robbery" if, in order to the committing of the theft, or in committing the theft, or in carrying away or attempting to carry away property obtained by the theft, the offender, for that end, voluntarily causes or attempts to cause to any person death or hurt or wrongful restraint...
                </div>
              </div>
              
              <div className="grid grid-cols-2 gap-4">
                <div className="bg-surface border border-border-soft p-4 rounded-lg">
                  <h4 className="text-xs font-bold uppercase tracking-wider text-text-faint mb-2">Punishment</h4>
                  <p className="text-sm text-text font-semibold text-danger-bright">Rigorous imprisonment up to 10 years + Fine</p>
                </div>
                <div className="bg-surface border border-border-soft p-4 rounded-lg">
                  <h4 className="text-xs font-bold uppercase tracking-wider text-text-faint mb-2">BNSS Procedure</h4>
                  <p className="text-sm text-text font-semibold text-accent-bright">Cognizable, Non-bailable</p>
                </div>
              </div>
            </div>
          </div>
          
          <div className="glass rounded-xl p-6 border-accent/20">
            <h3 className="text-sm font-bold uppercase tracking-wider text-accent-bright mb-4 flex items-center gap-2">
              <SparklesIcon /> AI Legal Reasoning Example
            </h3>
            <p className="text-sm text-text-dim mb-4 leading-relaxed">
              Based on recent FIR narratives regarding "chain snatching on bikes", the Intelligence Engine recommends examining the applicability of <strong>BNS Sec 304 (Snatching)</strong> rather than general theft (Sec 303), as snatching carries a distinct, non-bailable procedural framework under BNSS.
            </p>
            <button className="text-xs font-bold bg-accent/20 text-accent-bright px-3 py-1.5 rounded hover:bg-accent/30 transition-colors">
              Scan Active Cases for Sec 304 Applicability
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

function SparklesIcon() {
  return <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z"/></svg>
}
