import React, { useState } from 'react';
import { Scale, Search, ShieldAlert } from 'lucide-react';
import { BNS_PROVISIONS, HERO_CASE_PROVISIONS, LegalProvision } from '../mockServices/legalProvisionMockData';
import { LegalProvisionList } from '../components/legal/LegalProvisionList';
import { ProvisionDetailsDrawer } from '../components/legal/ProvisionDetailsDrawer';

// All provisions as an array for the searchable list
const ALL_PROVISIONS = Object.values(BNS_PROVISIONS);

export function LegalIntelligence() {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedFromList, setSelectedFromList] = useState<LegalProvision | null>(null);
  const [drawerProvision, setDrawerProvision] = useState<LegalProvision | null>(null);

  const filtered = ALL_PROVISIONS.filter(p =>
    p.section.toLowerCase().includes(searchTerm.toLowerCase()) ||
    p.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
    p.category.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const displayed = selectedFromList ? [{ ...selectedFromList, tier: 'PRIMARY' as const }] : HERO_CASE_PROVISIONS;

  return (
    <>
      <ProvisionDetailsDrawer provision={drawerProvision} onClose={() => setDrawerProvision(null)} />

      <div className="space-y-6 animate-fade-in max-w-7xl mx-auto">
        <div>
          <h2 className="text-2xl font-bold text-text font-display flex items-center gap-2">
            <Scale className="text-brand" /> Legal Intelligence
          </h2>
          <p className="text-sm text-text-dim mt-1">
            AI-assisted analysis of Bharatiya Nyaya Sanhita (BNS) and BNSS procedures.{' '}
            <span className="text-text-faint">Hover a provision to preview · Click to explore.</span>
          </p>
        </div>

        {/* Disclaimer */}
        <div className="bg-warning/10 border border-warning/30 p-4 rounded-xl flex items-start gap-3">
          <ShieldAlert className="text-warning shrink-0 mt-0.5" size={20} />
          <div>
            <h4 className="text-sm font-bold text-warning uppercase tracking-wider mb-1">
              AI-ASSISTED — REQUIRES AUTHORIZED OFFICER REVIEW
            </h4>
            <p className="text-xs text-text-dim">
              Legal intelligence is generated by analyzing case patterns against BNS provisions. It does not
              constitute final legal authority. All charges must be reviewed by the investigating officer
              before filing the charge sheet.
            </p>
          </div>
        </div>

        <div className="grid md:grid-cols-3 gap-6">
          {/* Left: searchable provision list */}
          <div className="md:col-span-1 space-y-4">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-text-dim" size={16} />
              <input
                type="text"
                placeholder="Search BNS provisions..."
                value={searchTerm}
                onChange={e => setSearchTerm(e.target.value)}
                className="w-full bg-surface border border-border-soft rounded-lg pl-9 pr-4 py-3 text-sm text-text focus:border-brand outline-none"
              />
            </div>

            <div className="glass rounded-xl p-4">
              <h3 className="font-bold text-sm uppercase tracking-wider text-text-dim mb-3 border-b border-border-soft pb-2">
                BNS Provisions Library
              </h3>
              <ul className="space-y-1">
                {filtered.map(p => (
                  <li key={p.section}>
                    <button
                      onClick={() => setSelectedFromList(p)}
                      className={`w-full text-left text-sm px-3 py-2.5 rounded-lg transition-colors flex items-center justify-between group ${
                        selectedFromList?.section === p.section
                          ? 'bg-surface-hover border-l-2 border-brand text-brand font-semibold'
                          : 'text-text hover:text-brand hover:bg-surface-hover'
                      }`}
                    >
                      <div>
                        <div className="font-mono text-[10px] text-text-faint">{p.section}</div>
                        <div className="font-semibold">{p.title}</div>
                      </div>
                      <span className={`text-[9px] font-bold px-1.5 py-0.5 rounded border ${
                        p.relevanceLevel === 'HIGH' ? 'text-success border-success/30 bg-success/10' :
                        p.relevanceLevel === 'MEDIUM' ? 'text-warning border-warning/30 bg-warning/10' :
                        'text-text-dim border-border bg-surface-2'
                      }`}>{p.relevanceLevel}</span>
                    </button>
                  </li>
                ))}
                {filtered.length === 0 && (
                  <li className="text-xs text-text-dim text-center py-4 italic">No provisions match your search.</li>
                )}
              </ul>
              {selectedFromList && (
                <button
                  onClick={() => setSelectedFromList(null)}
                  className="mt-3 text-[10px] text-text-faint hover:text-text transition-colors w-full text-center"
                >
                  ← Back to case provisions
                </button>
              )}
            </div>
          </div>

          {/* Right: provision cards */}
          <div className="md:col-span-2">
            <div className="glass rounded-xl p-6">
              <LegalProvisionList
                provisions={displayed}
                title={selectedFromList ? `${selectedFromList.section} — Detail` : 'Case-Applicable Provisions'}
                showDisclaimer={false}
              />
            </div>

            {/* AI reasoning example */}
            {!selectedFromList && (
              <div className="glass rounded-xl p-5 border-accent/20 mt-4">
                <h3 className="text-sm font-bold uppercase tracking-wider text-accent-bright mb-3 flex items-center gap-2">
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z"/></svg>
                  AI Legal Reasoning
                </h3>
                <p className="text-sm text-text-dim mb-4 leading-relaxed">
                  Based on recent FIR narratives regarding snatching incidents in Bhubaneswar district, the
                  Intelligence Engine recommends examining the applicability of{' '}
                  <strong>BNS §304 (Snatching)</strong> rather than general theft (§303), as snatching
                  carries a distinct, non-bailable procedural framework under BNSS.
                </p>
                <button
                  onClick={() => setDrawerProvision(BNS_PROVISIONS['BNS §304'])}
                  className="text-xs font-bold bg-accent/20 text-accent-bright px-3 py-1.5 rounded hover:bg-accent/30 transition-colors"
                >
                  View BNS §304 Provision →
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
    </>
  );
}
